module.exports = {
    // Venia-ui components
    '@magento/venia-ui/lib/components/App/app.js':
        '../lib/overrides/components/App/app.js',
    '@magento/venia-ui/lib/components/Main/main.js':
        '../lib/overrides/components/Main/main.js',
    '@magento/venia-ui/lib/components/Header/header.js':
        '../lib/overrides/components/Header/header.js',
    '@magento/venia-ui/lib/components/Footer/footer.js':
        '../lib/overrides/components/Footer/footer.js',
    '@magento/venia-ui/lib/components/CategoryTree/categoryTree.js':
        '../lib/overrides/components/CategoryTree/categoryTree.js',
    '@magento/venia-ui/lib/components/MegaMenu/megaMenu.js':
        '../lib/overrides/components/MegaMenu/megaMenu.js',
    '@magento/venia-ui/lib/components/MegaMenu/megaMenuItem.js':
        '../lib/overrides/components/MegaMenu/megaMenuItem.js',
    '@magento/venia-ui/lib/components/Button/button.js':
        '../lib/overrides/components/Button/button.js',
    '@magento/venia-ui/lib/components/TextInput/textInput.js':
        '../lib/overrides/components/TextInput/textInput.js',
    '@magento/venia-ui/lib/components/Checkbox/checkbox.js':
        '../lib/overrides/components/Checkbox/checkbox.js',
    '@magento/venia-ui/lib/components/SignIn/signIn.js':
        '../lib/overrides/components/SignIn/signIn.js',
    '@magento/venia-ui/lib/components/Navigation/navigation.js':
        '../lib/overrides/components/Navigation/navigation.js',
    '@magento/venia-ui/lib/components/AuthBar/authBar.js':
        '../lib/overrides/components/AuthBar/authBar.js',
    '@magento/venia-ui/lib/components/ForgotPassword/ForgotPasswordForm/forgotPasswordForm.js':
        '../lib/overrides/components/ForgotPassword/ForgotPasswordForm/forgotPasswordForm.js',
    '@magento/venia-ui/lib/components/Password/password.js':
        '../lib/overrides/components/Password/password.js',
    '@magento/venia-ui/lib/components/MiniCart/miniCart.js':
        '../lib/overrides/components/MiniCart/miniCart.js',
    '@magento/venia-ui/lib/components/SearchBar/searchBar.js':
        '../lib/overrides/components/SearchBar/searchBar.js',
    '@magento/venia-ui/lib/components/SearchBar/autocomplete.js':
        '../lib/overrides/components/SearchBar/autocomplete.js',
    '@magento/venia-ui/lib/components/SearchBar/suggestedCategory.js':
        '../lib/overrides/components/SearchBar/suggestedCategory.js',
    '@magento/venia-ui/lib/components/SearchBar/suggestedProduct.js':
        '../lib/overrides/components/SearchBar/suggestedProduct.js',
    '@magento/venia-ui/lib/components/CreateAccount/createAccount.js':
        '../lib/overrides/components/CreateAccount/createAccount.js',
    '@magento/venia-ui/lib/components/AccountMenu/accountMenuItems.js':
        '../lib/overrides/components/AccountMenu/accountMenuItems.js',
    '@magento/venia-ui/lib/components/AccountMenu/accountMenu.js':
        '../lib/overrides/components/AccountMenu/accountMenu.js',
    '@magento/venia-ui/lib/components/AccountChip/accountChip.js':
        '../lib/overrides/components/AccountChip/accountChip.js',
    '@magento/venia-ui/lib/components/Gallery/gallery.js':
        '../lib/overrides/components/Gallery/gallery.js',
    '@magento/venia-ui/lib/components/Breadcrumbs/breadcrumbs.js':
        '../lib/overrides/components/Breadcrumbs/breadcrumbs.js',
    '@magento/venia-ui/lib/components/Pagination/pagination.js':
        '../lib/overrides/components/Pagination/pagination.js',
    '@magento/venia-ui/lib/components/FilterModal/filterModal.js':
        '../lib/overrides/components/FilterModal/filterModal.js',
    '@magento/venia-ui/lib/components/FilterModal/filterBlock.js':
        '../lib/overrides/components/FilterModal/filterBlock.js',
    '@magento/venia-ui/lib/components/FilterModal/CurrentFilters/currentFilter.js':
        '../lib/overrides/components/FilterModal/CurrentFilters/currentFilter.js',
    '@magento/venia-ui/lib/components/ProductSort/productSort.js':
        '../lib/overrides/components/ProductSort/productSort.js',
    '@magento/venia-ui/lib/components/ProductFullDetail/productFullDetail.js':
        '../lib/overrides/components/ProductFullDetail/productFullDetail.js',
    '@magento/venia-ui/lib/components/ProductImageCarousel/carousel.js':
        '../lib/overrides/components/ProductImageCarousel/carousel.js',
    '@magento/venia-ui/lib/components/CartPage/ProductListing/quantity.js':
        '../lib/overrides/components/CartPage/ProductListing/quantity.js',
    '@magento/venia-ui/lib/components/CheckoutPage/checkoutPage.js':
        '../lib/overrides/components/CheckoutPage/checkoutPage.js',
    '@magento/venia-ui/lib/components/CartPage/cartPage.js':
        '../lib/overrides/components/CartPage/cartPage.js',
    '@magento/venia-ui/lib/components/Select/select.js':
        '../lib/overrides/components/Select/select.js',
    '@magento/venia-ui/lib/components/RadioGroup/radioGroup.js':
        '../lib/overrides/components/RadioGroup/radioGroup.js',
    '@magento/venia-ui/lib/components/RadioGroup/radio.js':
        '../lib/overrides/components/RadioGroup/radio.js',
    '@magento/venia-ui/lib/components/Dialog/dialog.js':
        '../lib/overrides/components/Dialog/dialog.js',
    '@magento/venia-ui/lib/components/LegacyMiniCart/kebab.js':
        '../lib/overrides/components/MiniCart/Kebab/kebab.js',
    '@magento/venia-ui/lib/components/CheckoutPage/BillingAddress/billingAddress.js':
        '../lib/overrides/components/CheckoutPage/BillingAddress/billingAddress.js',
    '@magento/venia-ui/lib/components/WishlistPage/wishlist.js':
        '../lib/overrides/components/WishlistPage/wishlist.js',
    '@magento/venia-ui/lib/components/WishlistPage/wishlistItem.js':
        '../lib/overrides/components/WishlistPage/wishlistItem.js',
    '@magento/venia-ui/lib/components/AccountInformationPage/accountInformationPage.js':
        '../lib/overrides/components/AccountInformationPage/accountInformationPage.js',
    '@magento/venia-ui/lib/components/LoadingIndicator/index.js':
        '../lib/overrides/components/LoadingIndicator/index.js',
    '@magento/venia-ui/lib/components/Price/price.js':
        '../lib/overrides/components/Price/price.js',

    // Styles
    '@magento/venia-ui/lib/components/MiniCart/miniCart.css':
        '../lib/overrides/components/MiniCart/miniCart.css',
    '@magento/venia-ui/lib/components/ForgotPassword/forgotPassword.css':
        '../lib/overrides/components/ForgotPassword/forgotPassword.css',
    '@magento/venia-ui/lib/components/LinkButton/linkButton.css':
        '../lib/overrides/components/LinkButton/linkButton.css',
    '@magento/venia-ui/lib/components/MiniCart/ProductList/productList.css':
        '../lib/overrides/components/MiniCart/ProductList/productList.css',
    '@magento/venia-ui/lib/components/SearchBar/suggestedCategories.css':
        '../lib/overrides/components/SearchBar/suggestedCategories.css',
    '@magento/venia-ui/lib/components/SearchBar/suggestedProducts.css':
        '../lib/overrides/components/SearchBar/suggestedProducts.css',
    '@magento/venia-ui/lib/components/FilterSidebar/filterSidebar.css':
        '../lib/overrides/components/FilterSidebar/filterSidebar.css',
    '@magento/venia-ui/lib/components/FilterSidebar/filterSidebar.css':
        '../lib/overrides/components/FilterSidebar/filterSidebar.css',
    '@magento/venia-ui/lib/components/ProductImageCarousel/thumbnail.css':
        '../lib/overrides/components/ProductImageCarousel/thumbnail.css',
    '@magento/venia-ui/lib/components/ProductOptions/option.css':
        '../lib/overrides/components/ProductOptions/option.css',

    // RootComponents
    '@magento/venia-ui/lib/RootComponents/Category/categoryContent.js':
        '../lib/overrides/RootComponents/Category/categoryContent.js',
    '@magento/venia-ui/lib/RootComponents/CMS/cms.js':
        '../lib/overrides/RootComponents/CMS/cms.js',

    // Pagebuilder components
    '@magento/pagebuilder/lib/ContentTypes/Row/row.js':
        '../lib/overrides/pagebuilder/Layout/Row/row.js',
    '@magento/pagebuilder/lib/ContentTypes/Column/column.js':
        '../lib/overrides/pagebuilder/Layout/Column/column.js',
    '@magento/pagebuilder/lib/ContentTypes/Tabs/tabs.js':
        '../lib/overrides/pagebuilder/Layout/Tabs/tabs.js',
    '@magento/pagebuilder/lib/ContentTypes/Image/image.js':
        '../lib/overrides/pagebuilder/Media/Image/image.js',
    '@magento/pagebuilder/lib/ContentTypes/Banner/banner.js':
        '../lib/overrides/pagebuilder/Media/Banner/banner.js',
    '@magento/pagebuilder/lib/ContentTypes/Slider/slider.js':
        '../lib/overrides/pagebuilder/Media/Slider/slider.js',
    '@magento/pagebuilder/lib/ContentTypes/Products/products.js':
        '../lib/overrides/pagebuilder/AddContent/Products/products.js',

    // Talons
    '@magento/peregrine/lib/talons/Header/useCartTrigger.js':
        '../lib/overrides/talons/Header/useCartTrigger.js',
    '@magento/peregrine/lib/talons/AccountMenu/useAccountMenuItems.js':
        '../lib/overrides/talons/AccountMenu/useAccountMenuItems.js',
    '@magento/peregrine/lib/talons/SearchBar/useSearchBar.js':
        '../lib/overrides/talons/SearchBar/useSearchBar.js',
    '@magento/peregrine/lib/talons/MegaMenu/useMegaMenu.js':
        '../lib/overrides/talons/MegaMenu/useMegaMenu.js',
    '@magento/peregrine/lib/talons/Wishlist/AddToListButton/helpers/useSingleWishlist.js':
        '../lib/overrides/talons/Wishlist/useSingleWishlist.js',
    '@magento/peregrine/lib/talons/AuthBar/useAuthBar.js':
        '../lib/overrides/talons/AuthBar/useAuthBar.js',
    '@magento/peregrine/lib/talons/AccountInformationPage/useAccountInformationPage.js':
        '../lib/overrides/talons/AccountInformationPage/useAccountInformationPage.js',
    '@magento/peregrine/lib/talons/CartPage/PriceSummary/usePriceSummary.js':
        '../lib/overrides/talons/CartPage/usePriceSummary.js',
    '@magento/peregrine/lib/talons/MiniCart/useMiniCart.js':
        '../lib/overrides/talons/MiniCart/useMiniCart.js',

    // Utils
    '@magento/venia-ui/lib/util/formValidators.js':
        '../lib/overrides/util/formValidators.js',

    // Queries
    '@magento/venia-ui/lib/components/AccountChip/accountChip.gql.js':
        '../lib/overrides/components/AccountChip/accountChip.gql.js',
    '@magento/peregrine/lib/talons/MegaMenu/megaMenu.gql.js':
        '../lib/overrides/talons/MegaMenu/megaMenu.gql.js',
    '@magento/peregrine/lib/talons/MiniCart/ProductList/productListFragments.gql.js':
        '../lib/overrides/talons/MiniCart/productListFragments.gql.js'
};
